spring.application.name=Demo2222026
server.port=8761

# Eureka Server không c?n t? ??ng ký chính nó
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# T?t ch? ?? b?o v? (Self Preservation) ?? d? quan sát khi th?c hành Lab
eureka.server.enable-self-preservation=false
# Th?i gian quét ??nh k? ?? lo?i b? các service không g?i heartbeat (ms)
eureka.server.eviction-interval-timer-in-ms=5000
#spring.cloud.service-registry.auto-registration.enabled=false