spring.application.name=appointment-service
server.port=8091
spring.config.import=configserver:http://localhost:8888

management.endpoints.web.exposure.include=refresh

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.patientRetry.max-attempts=3
resilience4j.retry.instances.patientRetry.wait-duration=2s
resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException


logging.level.io.github.resilience4j=DEBUG
