
  mail:
    host: smtp.gmail.com
    port: 587
    username: huongcaoha1995@gmail.com
    password: zeqo ydec dzzi wkzy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_session10_kafka_pharmacy_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pharmacy-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.example.pharmacykafka.model.dto.request.OrderEvent
